//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDoZe_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe_WPF.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string labelBairro_Content {
            get {
                return ResourceManager.GetString("labelBairro.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string LabelCep_Content {
            get {
                return ResourceManager.GetString("LabelCep.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string labelCidade_Content {
            get {
                return ResourceManager.GetString("labelCidade.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string labelLogradouro_Content {
            get {
                return ResourceManager.GetString("labelLogradouro.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string labelPais_Content {
            get {
                return ResourceManager.GetString("labelPais.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF.
        /// </summary>
        public static string LabelUf_Content {
            get {
                return ResourceManager.GetString("LabelUf.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno.
        /// </summary>
        public static string txtAluno {
            get {
                return ResourceManager.GetString("txtAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aulas.
        /// </summary>
        public static string txtAulas {
            get {
                return ResourceManager.GetString("txtAulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação.
        /// </summary>
        public static string txtAvaliacao {
            get {
                return ResourceManager.GetString("txtAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador.
        /// </summary>
        public static string txtColaborador {
            get {
                return ResourceManager.GetString("txtColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequência.
        /// </summary>
        public static string txtFrequencia {
            get {
                return ResourceManager.GetString("txtFrequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string txtHome {
            get {
                return ResourceManager.GetString("txtHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon/logoff.
        /// </summary>
        public static string txtLogin {
            get {
                return ResourceManager.GetString("txtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string txtLogradouro {
            get {
                return ResourceManager.GetString("txtLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricula.
        /// </summary>
        public static string txtMatricula {
            get {
                return ResourceManager.GetString("txtMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string txtSenha {
            get {
                return ResourceManager.GetString("txtSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treinos.
        /// </summary>
        public static string txtTreinos {
            get {
                return ResourceManager.GetString("txtTreinos", resourceCulture);
            }
        }
    }
}
